Ignore codelabs repo
Map codelabs to codelabs
Backup codelabs
(1/3) Downloading...
Starting git clone https://gitee.com/openharmony/codelabs.git
Starting git clone https://gitee.com/openharmony/codelabs.git
Starting git clone https://gitee.com/openharmony/codelabs.git
(1/3) Downloading...
Starting git clone https://gitee.com/openharmony/codelabs.git
Starting git clone https://gitee.com/openharmony/codelabs.git
Starting git clone https://gitee.com/openharmony/codelabs.git
(1/3) Downloading...
Starting git clone https://gitee.com/openharmony/codelabs.git
Starting git clone https://gitee.com/openharmony/codelabs.git
Starting git clone https://gitee.com/openharmony/codelabs.git
Cmd('git') failed due to: exit code(128)
  cmdline: git clone https://gitee.com/openharmony/codelabs.git /github/workspace/hub-mirror-cache/codelabs
  stderr: 'Cloning into '/github/workspace/hub-mirror-cache/codelabs'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 5082 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output'

Signed-off-by: Stefan Schmidt <stefan.schmidt@huawei.com>