Does not exist anymore
raceback (most recent call last):
  File "/home/runner/work/mirror-sync/mirror-sync/.github/workflows/split-list.py", line 10, in <module>
    lst.remove("hiviewdfx_hisysevent")
ValueError: list.remove(x): x not in list
Error: Process completed with exit code 1.

Signed-off-by: Stefan Schmidt <stefan.schmidt@huawei.com>